#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall
RESINC = 
LIBDIR = 
LIB = -lSDL2
LDFLAGS = 

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/Game

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/Game

OBJ_DEBUG = $(OBJDIR_DEBUG)/src/KeyHandler.o $(OBJDIR_DEBUG)/src/Main.o $(OBJDIR_DEBUG)/src/Map/Map.o $(OBJDIR_DEBUG)/src/Map/MapReader.o $(OBJDIR_DEBUG)/src/Physics/Physics.o $(OBJDIR_DEBUG)/src/Player.o $(OBJDIR_DEBUG)/src/ScriptReader.o $(OBJDIR_DEBUG)/src/States/IntroState.o $(OBJDIR_DEBUG)/src/States/MenuState.o $(OBJDIR_DEBUG)/src/States/PlayingState.o $(OBJDIR_DEBUG)/src/Unit.o $(OBJDIR_DEBUG)/src/WorldObject.o $(OBJDIR_DEBUG)/src/GameEngine.o $(OBJDIR_DEBUG)/src/Animation/AnimationNode.o $(OBJDIR_DEBUG)/src/Animation/AnimationReader.o $(OBJDIR_DEBUG)/src/Animation/Sprite.o $(OBJDIR_DEBUG)/src/Camera.o $(OBJDIR_DEBUG)/src/Animation/Animation.o $(OBJDIR_DEBUG)/src/GraphicHelper.o $(OBJDIR_DEBUG)/src/InputHandler.o $(OBJDIR_DEBUG)/src/Item/Armor.o $(OBJDIR_DEBUG)/src/Item/Item.o $(OBJDIR_DEBUG)/src/Item/Weapon.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/src/KeyHandler.o $(OBJDIR_RELEASE)/src/Main.o $(OBJDIR_RELEASE)/src/Map/Map.o $(OBJDIR_RELEASE)/src/Map/MapReader.o $(OBJDIR_RELEASE)/src/Physics/Physics.o $(OBJDIR_RELEASE)/src/Player.o $(OBJDIR_RELEASE)/src/ScriptReader.o $(OBJDIR_RELEASE)/src/States/IntroState.o $(OBJDIR_RELEASE)/src/States/MenuState.o $(OBJDIR_RELEASE)/src/States/PlayingState.o $(OBJDIR_RELEASE)/src/Unit.o $(OBJDIR_RELEASE)/src/WorldObject.o $(OBJDIR_RELEASE)/src/GameEngine.o $(OBJDIR_RELEASE)/src/Animation/AnimationNode.o $(OBJDIR_RELEASE)/src/Animation/AnimationReader.o $(OBJDIR_RELEASE)/src/Animation/Sprite.o $(OBJDIR_RELEASE)/src/Camera.o $(OBJDIR_RELEASE)/src/Animation/Animation.o $(OBJDIR_RELEASE)/src/GraphicHelper.o $(OBJDIR_RELEASE)/src/InputHandler.o $(OBJDIR_RELEASE)/src/Item/Armor.o $(OBJDIR_RELEASE)/src/Item/Item.o $(OBJDIR_RELEASE)/src/Item/Weapon.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG)/src || mkdir -p $(OBJDIR_DEBUG)/src
	test -d $(OBJDIR_DEBUG)/src/Map || mkdir -p $(OBJDIR_DEBUG)/src/Map
	test -d $(OBJDIR_DEBUG)/src/Physics || mkdir -p $(OBJDIR_DEBUG)/src/Physics
	test -d $(OBJDIR_DEBUG)/src/States || mkdir -p $(OBJDIR_DEBUG)/src/States
	test -d $(OBJDIR_DEBUG)/src/Animation || mkdir -p $(OBJDIR_DEBUG)/src/Animation
	test -d $(OBJDIR_DEBUG)/src/Item || mkdir -p $(OBJDIR_DEBUG)/src/Item

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/src/KeyHandler.o: src/KeyHandler.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/KeyHandler.cpp -o $(OBJDIR_DEBUG)/src/KeyHandler.o

$(OBJDIR_DEBUG)/src/Main.o: src/Main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Main.cpp -o $(OBJDIR_DEBUG)/src/Main.o

$(OBJDIR_DEBUG)/src/Map/Map.o: src/Map/Map.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Map/Map.cpp -o $(OBJDIR_DEBUG)/src/Map/Map.o

$(OBJDIR_DEBUG)/src/Map/MapReader.o: src/Map/MapReader.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Map/MapReader.cpp -o $(OBJDIR_DEBUG)/src/Map/MapReader.o

$(OBJDIR_DEBUG)/src/Physics/Physics.o: src/Physics/Physics.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Physics/Physics.cpp -o $(OBJDIR_DEBUG)/src/Physics/Physics.o

$(OBJDIR_DEBUG)/src/Player.o: src/Player.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Player.cpp -o $(OBJDIR_DEBUG)/src/Player.o

$(OBJDIR_DEBUG)/src/ScriptReader.o: src/ScriptReader.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/ScriptReader.cpp -o $(OBJDIR_DEBUG)/src/ScriptReader.o

$(OBJDIR_DEBUG)/src/States/IntroState.o: src/States/IntroState.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/States/IntroState.cpp -o $(OBJDIR_DEBUG)/src/States/IntroState.o

$(OBJDIR_DEBUG)/src/States/MenuState.o: src/States/MenuState.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/States/MenuState.cpp -o $(OBJDIR_DEBUG)/src/States/MenuState.o

$(OBJDIR_DEBUG)/src/States/PlayingState.o: src/States/PlayingState.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/States/PlayingState.cpp -o $(OBJDIR_DEBUG)/src/States/PlayingState.o

$(OBJDIR_DEBUG)/src/Unit.o: src/Unit.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Unit.cpp -o $(OBJDIR_DEBUG)/src/Unit.o

$(OBJDIR_DEBUG)/src/WorldObject.o: src/WorldObject.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/WorldObject.cpp -o $(OBJDIR_DEBUG)/src/WorldObject.o

$(OBJDIR_DEBUG)/src/GameEngine.o: src/GameEngine.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/GameEngine.cpp -o $(OBJDIR_DEBUG)/src/GameEngine.o

$(OBJDIR_DEBUG)/src/Animation/AnimationNode.o: src/Animation/AnimationNode.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Animation/AnimationNode.cpp -o $(OBJDIR_DEBUG)/src/Animation/AnimationNode.o

$(OBJDIR_DEBUG)/src/Animation/AnimationReader.o: src/Animation/AnimationReader.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Animation/AnimationReader.cpp -o $(OBJDIR_DEBUG)/src/Animation/AnimationReader.o

$(OBJDIR_DEBUG)/src/Animation/Sprite.o: src/Animation/Sprite.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Animation/Sprite.cpp -o $(OBJDIR_DEBUG)/src/Animation/Sprite.o

$(OBJDIR_DEBUG)/src/Camera.o: src/Camera.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Camera.cpp -o $(OBJDIR_DEBUG)/src/Camera.o

$(OBJDIR_DEBUG)/src/Animation/Animation.o: src/Animation/Animation.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Animation/Animation.cpp -o $(OBJDIR_DEBUG)/src/Animation/Animation.o

$(OBJDIR_DEBUG)/src/GraphicHelper.o: src/GraphicHelper.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/GraphicHelper.cpp -o $(OBJDIR_DEBUG)/src/GraphicHelper.o

$(OBJDIR_DEBUG)/src/InputHandler.o: src/InputHandler.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/InputHandler.cpp -o $(OBJDIR_DEBUG)/src/InputHandler.o

$(OBJDIR_DEBUG)/src/Item/Armor.o: src/Item/Armor.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Item/Armor.cpp -o $(OBJDIR_DEBUG)/src/Item/Armor.o

$(OBJDIR_DEBUG)/src/Item/Item.o: src/Item/Item.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Item/Item.cpp -o $(OBJDIR_DEBUG)/src/Item/Item.o

$(OBJDIR_DEBUG)/src/Item/Weapon.o: src/Item/Weapon.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Item/Weapon.cpp -o $(OBJDIR_DEBUG)/src/Item/Weapon.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)/src
	rm -rf $(OBJDIR_DEBUG)/src/Map
	rm -rf $(OBJDIR_DEBUG)/src/Physics
	rm -rf $(OBJDIR_DEBUG)/src/States
	rm -rf $(OBJDIR_DEBUG)/src/Animation
	rm -rf $(OBJDIR_DEBUG)/src/Item

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src
	test -d $(OBJDIR_RELEASE)/src/Map || mkdir -p $(OBJDIR_RELEASE)/src/Map
	test -d $(OBJDIR_RELEASE)/src/Physics || mkdir -p $(OBJDIR_RELEASE)/src/Physics
	test -d $(OBJDIR_RELEASE)/src/States || mkdir -p $(OBJDIR_RELEASE)/src/States
	test -d $(OBJDIR_RELEASE)/src/Animation || mkdir -p $(OBJDIR_RELEASE)/src/Animation
	test -d $(OBJDIR_RELEASE)/src/Item || mkdir -p $(OBJDIR_RELEASE)/src/Item

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/src/KeyHandler.o: src/KeyHandler.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/KeyHandler.cpp -o $(OBJDIR_RELEASE)/src/KeyHandler.o

$(OBJDIR_RELEASE)/src/Main.o: src/Main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Main.cpp -o $(OBJDIR_RELEASE)/src/Main.o

$(OBJDIR_RELEASE)/src/Map/Map.o: src/Map/Map.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Map/Map.cpp -o $(OBJDIR_RELEASE)/src/Map/Map.o

$(OBJDIR_RELEASE)/src/Map/MapReader.o: src/Map/MapReader.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Map/MapReader.cpp -o $(OBJDIR_RELEASE)/src/Map/MapReader.o

$(OBJDIR_RELEASE)/src/Physics/Physics.o: src/Physics/Physics.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Physics/Physics.cpp -o $(OBJDIR_RELEASE)/src/Physics/Physics.o

$(OBJDIR_RELEASE)/src/Player.o: src/Player.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Player.cpp -o $(OBJDIR_RELEASE)/src/Player.o

$(OBJDIR_RELEASE)/src/ScriptReader.o: src/ScriptReader.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/ScriptReader.cpp -o $(OBJDIR_RELEASE)/src/ScriptReader.o

$(OBJDIR_RELEASE)/src/States/IntroState.o: src/States/IntroState.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/States/IntroState.cpp -o $(OBJDIR_RELEASE)/src/States/IntroState.o

$(OBJDIR_RELEASE)/src/States/MenuState.o: src/States/MenuState.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/States/MenuState.cpp -o $(OBJDIR_RELEASE)/src/States/MenuState.o

$(OBJDIR_RELEASE)/src/States/PlayingState.o: src/States/PlayingState.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/States/PlayingState.cpp -o $(OBJDIR_RELEASE)/src/States/PlayingState.o

$(OBJDIR_RELEASE)/src/Unit.o: src/Unit.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Unit.cpp -o $(OBJDIR_RELEASE)/src/Unit.o

$(OBJDIR_RELEASE)/src/WorldObject.o: src/WorldObject.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/WorldObject.cpp -o $(OBJDIR_RELEASE)/src/WorldObject.o

$(OBJDIR_RELEASE)/src/GameEngine.o: src/GameEngine.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/GameEngine.cpp -o $(OBJDIR_RELEASE)/src/GameEngine.o

$(OBJDIR_RELEASE)/src/Animation/AnimationNode.o: src/Animation/AnimationNode.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Animation/AnimationNode.cpp -o $(OBJDIR_RELEASE)/src/Animation/AnimationNode.o

$(OBJDIR_RELEASE)/src/Animation/AnimationReader.o: src/Animation/AnimationReader.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Animation/AnimationReader.cpp -o $(OBJDIR_RELEASE)/src/Animation/AnimationReader.o

$(OBJDIR_RELEASE)/src/Animation/Sprite.o: src/Animation/Sprite.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Animation/Sprite.cpp -o $(OBJDIR_RELEASE)/src/Animation/Sprite.o

$(OBJDIR_RELEASE)/src/Camera.o: src/Camera.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Camera.cpp -o $(OBJDIR_RELEASE)/src/Camera.o

$(OBJDIR_RELEASE)/src/Animation/Animation.o: src/Animation/Animation.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Animation/Animation.cpp -o $(OBJDIR_RELEASE)/src/Animation/Animation.o

$(OBJDIR_RELEASE)/src/GraphicHelper.o: src/GraphicHelper.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/GraphicHelper.cpp -o $(OBJDIR_RELEASE)/src/GraphicHelper.o

$(OBJDIR_RELEASE)/src/InputHandler.o: src/InputHandler.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/InputHandler.cpp -o $(OBJDIR_RELEASE)/src/InputHandler.o

$(OBJDIR_RELEASE)/src/Item/Armor.o: src/Item/Armor.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Item/Armor.cpp -o $(OBJDIR_RELEASE)/src/Item/Armor.o

$(OBJDIR_RELEASE)/src/Item/Item.o: src/Item/Item.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Item/Item.cpp -o $(OBJDIR_RELEASE)/src/Item/Item.o

$(OBJDIR_RELEASE)/src/Item/Weapon.o: src/Item/Weapon.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Item/Weapon.cpp -o $(OBJDIR_RELEASE)/src/Item/Weapon.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)/src
	rm -rf $(OBJDIR_RELEASE)/src/Map
	rm -rf $(OBJDIR_RELEASE)/src/Physics
	rm -rf $(OBJDIR_RELEASE)/src/States
	rm -rf $(OBJDIR_RELEASE)/src/Animation
	rm -rf $(OBJDIR_RELEASE)/src/Item

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

